{
  programs.mangohud = {
    enable = true;
  };
  home.file.".config/MangoHud/MangoHud.conf".text = ''
legacy_layout=false
background_alpha=0.2
round_corners=0
background_alpha=0.2
background_color=020202
font_size=22
text_color=FFFFFF
position=top-left
toggle_hud=Shift_R+F12
no_display
pci_dev=0:01:00.0
table_columns=3
gpu_text=GPU
gpu_stats
gpu_load_change
gpu_load_value=50,90
gpu_load_color=FFFFFF,FFAA7F,CC0000
gpu_temp
gpu_mem_temp
gpu_color=2E9762
cpu_text=CPU
cpu_stats
core_bars
cpu_load_change
cpu_load_value=50,90
cpu_load_color=FFFFFF,FFAA7F,CC0000
cpu_mhz
cpu_temp
cpu_color=2E97CB
vram
vram_color=AD64C1
ram
ram_color=C26693
fps
gpu_name
vulkan_driver
arch
frame_timing
frametime_color=00FF00
fps_limit_method=late
toggle_fps_limit=none
show_fps_limit
fps_limit=0,240,144,90,60,30
fps_color_change
fps_color=B22222,FDFD09,39F900
fps_value=30,60
#offset=0
output_folder=/home/whyoolw
log_duration=0
autostart_log=0
log_interval=0
toggle_logging=Shift_L+F2
'';
}